version: "3.3"
services:
  boucan:
    build:
      context: ${BOUCAN_DIR}/boucanpy
      dockerfile: Dockerfile
    image: 3lpsy/boucan:latest
    networks:
      boucanpub:
    command: api-server -l 0.0.0.0 --db-setup --db-seed-env --log-level info --log-format short --second-log-level warning --force-exit
    env_file:
      - ${COMPOSE_ENV_DIR}/api.env
    depends_on:
      - db
      - broadcast
  dns:
    image: 3lpsy/boucan:latest
    networks:
      boucanpub:
    command: dns-server -l 0.0.0.0 -p 53 --log-level info --log-format short --no-ssl-verify
    ports:
      - "0.0.0.0:53:53/udp"
      - "0.0.0.0:53:53/tcp"
    env_file:
      - ${COMPOSE_ENV_DIR}/dns.env
    restart: on-failure:2
    depends_on:
      - boucan
      - broadcast
      - web
  http:
    image: 3lpsy/boucan:latest
    networks:
      boucanpub:
    command: http-server -l 0.0.0.0 -p 80 --log-level info --log-format short --no-ssl-verify --enable-ssl --ssl-port 443 --ssl-listen 0.0.0.0 --ssl-key-path  /etc/letsencrypt/live/boucan.proxy.docker/privkey.pem --ssl-cert-path /etc/letsencrypt/live/boucan.proxy.docker/fullchain.pem
    ports:
      - "0.0.0.0:80:80/tcp"
      - "0.0.0.0:443:443/tcp"
    env_file:
      - ${COMPOSE_ENV_DIR}/http.env
    volumes:
      - /etc/letsencrypt/live/bountydns.proxy.docker:/etc/letsencrypt/live/boucan.proxy.docker
    restart: on-failure:2
    depends_on:
      - boucan
      - broadcast
      - web
  web:
    build:
      context: ${BOUCAN_DIR}/boucan-web
      dockerfile: Dockerfile
    image: 3lpsy/boucan-web:latest
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8443:8443"
    env_file:
      - ${COMPOSE_ENV_DIR}/web.env
    networks:
      boucanpub:
    depends_on:
      - boucan
  broadcast:
    build:
      context: ${COMPOSE_DIR}/broadcast
      dockerfile: Dockerfile
    image: 3lpsy/boucan-broadcast:latest
    ports:
      - "127.0.0.1:6379:6379"
    env_file:
      - ${COMPOSE_ENV_DIR}/broadcast.env
    networks:
      boucanpub:
    restart: on-failure:5
  db:
    image: postgres:latest
    env_file:
      - ${COMPOSE_ENV_DIR}/db.env
    networks:
      boucanpub:
networks:
  boucanpub:
    # Use a custom driver
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.20.0/24
    driver_opts:
      com.docker.network.bridge.name: boucanpub0
